/*
 * patch-stars.js — re-anchor star thresholds in the SHIPPED js/levels.js
 * without touching anything else (boards, refills, moves, win targets all stay
 * byte-identical; stars are not part of the mid-level save signature, so no
 * player save or progress is disturbed).
 *
 * v3 star rule (also in build-levels.js starThresholds for future builds):
 *   star1 = winTarget (you win)
 *   star2 = 1.15 x winTarget
 *   star3 = 1.35 x winTarget
 * clamped to min(maxScore, certTarget) — never demands more than "good play",
 * and maxScore is an exhibited reachable line so 3 stars is always attainable.
 *
 * Run: node scripts/patch-stars.js
 */
"use strict";
var fs = require("fs");
var path = require("path");

function round60(x) { return Math.round(x / 60) * 60; }

var file = path.join(__dirname, "..", "js", "levels.js");
global.window = {};
require(file);
var levels = window.CANDY_LEVELS;

var changed = 0;
levels.forEach(function (l) {
  var win = l.target;
  var star2 = round60(win * 1.15);
  var star3 = round60(win * 1.35);
  var ceil = Math.min(l.maxScore, l.certTarget);
  if (star3 > ceil) star3 = round60(ceil);
  if (star2 >= star3) star2 = star3 - 60;
  if (star2 <= win) star2 = win + 60;
  if (star3 <= star2) star3 = star2 + 60;
  if (star3 > l.maxScore) star3 = round60(l.maxScore);
  if (star2 > star3) star2 = star3;
  if (star2 !== l.star2 || star3 !== l.star3) changed++;
  l.star2 = star2; l.star3 = star3;
});

var header =
  "/* AUTO-GENERATED by scripts/build-levels.js — do not edit by hand.\n" +
  " * The Tide Pool \"Depths\" campaign, pre-verified by the solver.\n" +
  " * Star thresholds re-anchored by scripts/patch-stars.js (v3 star rule).\n" +
  " * Each entry: { depth, tier, rows, cols, colorCount, moves, target,\n" +
  " *   certTarget, star2, star3, maxScore, par, board:{rows,cols,grid},\n" +
  " *   refill:[[...]] }. Per-column refill pointers default to all-zero.\n" +
  " * Regenerate fully: node scripts/build-levels.js  (see that file). */\n";
fs.writeFileSync(file, header + "window.CANDY_LEVELS = " + JSON.stringify(levels) + ";\n");

console.log("Patched star thresholds on " + changed + "/" + levels.length + " depths.");
var show = [1, 2, 12, 18, 24, 25, 100];
show.forEach(function (d) {
  var l = levels[d - 1];
  console.log(" Depth " + String(d).padStart(3) + "  win " + String(l.target).padStart(6) +
    "  stars " + String(l.star2).padStart(6) + "/" + String(l.star3).padStart(6) +
    "  (cert " + l.certTarget + ", max " + l.maxScore + ")");
});
